class AtmRunner{
public static void main(String[] withdraw){
Atm machine =new Atm();
machine.branch="soraba";
machine.id=1;
machine.colour="black";
machine.weight=520;
System.out.println("---------------------");
System.out.println("The branch is "+machine.branch);
System.out.println("The id is "+machine.id);
System.out.println("The colour is"+machine.colour);
System.out.println("The weight is "+machine.weight);

Atm machine1=new Atm();
 machine1.branch="bengaluru";
 machine1.id=2;
 machine1.colour="green";
 machine1.weight=450;
System.out.println("-----------------------");
System.out.println("The branch is "+machine1.branch);
System.out.println("The id is "+machine1.id);
System.out.println("The colour is"+machine1.colour);
System.out.println("The weight is "+machine1.weight);

Atm machine2=new Atm();
 machine2.branch="benglure";
 machine2.id=3;
 machine2.colour="blue";
 machine2.weight=450;
System.out.println("---------------------");
System.out.println("The branch is "+machine2.branch);
System.out.println("The id is "+machine2.id);
System.out.println("The colour is"+machine2.colour);
System.out.println("The weight is "+machine2.weight);

Atm machine3=new Atm();
 machine3.branch="tumkur";
 machine3.id=4;
 machine3.colour="blue";
 machine3.weight=400;
System.out.println("---------------------");
System.out.println("The branch is "+machine3.branch);
System.out.println("The id is "+machine3.id);
System.out.println("The colour is"+machine3.colour);
System.out.println("The weight is "+machine3.weight);

Atm machine4=new Atm();
 machine4.branch="shivamogga";
 machine4.id=5;
 machine4.colour="black";
 machine4.weight=490;
System.out.println("---------------------");
System.out.println("The branch is "+machine4.branch);
System.out.println("The id is "+machine4.id);
System.out.println("The colour is"+machine4.colour);
System.out.println("The weight is "+machine4.weight);

Atm machine5=new Atm();
 machine5.branch="sagara";
 machine5.id=6;
 machine5.colour="black";
 machine5.weight=400;
System.out.println("---------------------");
System.out.println("The branch is "+machine5.branch);
System.out.println("The id is "+machine5.id);
System.out.println("The colour is"+machine5.colour);
System.out.println("The weight is "+machine5.weight);

Atm machine6 =new Atm();
 machine6.branch="hosanagar";
 machine6.id=7;
 machine6.colour="black";
 machine6.weight=800;
System.out.println("---------------------");
System.out.println("The branch is "+machine6.branch);
System.out.println("The id is "+machine6.id);
System.out.println("The colour is"+machine6.colour);
System.out.println("The weight is "+machine6.weight);

Atm machine7=new Atm();
 machine7.branch="vidyaranyapur";
 machine7.id=8;
 machine7.colour="black";
 machine7.weight=700;
System.out.println("---------------------");
System.out.println("The branch is "+machine7.branch);
System.out.println("The id is "+machine7.id);
System.out.println("The colour is"+machine7.colour);
System.out.println("The weight is "+machine7.weight);
Atm machine8=new Atm();
 machine8.branch="udupi";
 machine8.id=5;
 machine8.colour="black";
 machine8.weight=490;
System.out.println("---------------------");
System.out.println("The branch is "+machine8.branch);
System.out.println("The id is "+machine8.id);
System.out.println("The colour is"+machine8.colour);
System.out.println("The weight is "+machine8.weight);
Atm machine9=new Atm();
 machine9.branch="badravati";
 machine9.id=9;
 machine9.colour="black";
 machine9.weight=490;
System.out.println("---------------------");
System.out.println("The branch is "+machine9.branch);
System.out.println("The id is "+machine9.id);
System.out.println("The colour is"+machine9.colour);
System.out.println("The weight is "+machine9.weight);
Atm machine10=new Atm();
 machine10.branch="mugilpete";
 machine10.id=10;
 machine10.colour="black";
 machine10.weight=490;
System.out.println("---------------------");
System.out.println("The branch is "+machine10.branch);
System.out.println("The id is "+machine10.id);
System.out.println("The colour is"+machine10.colour);
System.out.println("The weight is "+machine10.weight);
Atm machine11=new Atm();
 machine11.branch="nagara";
 machine11.id=11;
 machine11.colour="black";
 machine11.weight=490;
System.out.println("---------------------");
System.out.println("The branch is "+machine11.branch);
System.out.println("The id is "+machine11.id);
System.out.println("The colour is"+machine11.colour);
System.out.println("The weight is "+machine11.weight);
Atm machine12=new Atm();
 machine12.branch="kumta";
 machine12.id=12;
 machine12.colour="black";
 machine12.weight=490;
System.out.println("---------------------");
System.out.println("The branch is "+machine12.branch);
System.out.println("The id is "+machine12.id);
System.out.println("The colour is"+machine12.colour);
System.out.println("The weight is "+machine12.weight);
Atm machine13=new Atm();
 machine13.branch="rajajinagar";
 machine13.id=13;
 machine13.colour="black";
 machine13.weight=490;
System.out.println("---------------------");
System.out.println("The branch is "+machine13.branch);
System.out.println("The id is "+machine13.id);
System.out.println("The colour is"+machine13.colour);
System.out.println("The weight is "+machine13.weight);
Atm machine14=new Atm();
 machine14.branch="yelahanka";
 machine14.id=14;
 machine14.colour="black";
 machine14.weight=490;
System.out.println("---------------------");
System.out.println("The branch is "+machine14.branch);
System.out.println("The id is "+machine14.id);
System.out.println("The colour is"+machine14.colour);
System.out.println("The weight is "+machine14.weight);
Atm machine15=new Atm();
 machine15.branch="mangalore";
 machine15.id=15;
 machine15.colour="black";
 machine15.weight=490;
System.out.println("---------------------");
System.out.println("The branch is "+machine15.branch);
System.out.println("The id is "+machine15.id);
System.out.println("The colour is"+machine15.colour);
System.out.println("The weight is "+machine15.weight);
}


}